title: Opération Libre
email: contact@operation-libre.org
description: Opération Libre c''est 48 heures d''animations participatives, pour collecter et libérer les informations et outils d''une commune avec les habitants, des associations et contributeurs
keywords: opendata, OSM, médiawiki, wikimédia, mapillary, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://libertic.github.io/opl-website/"
twitter_username: operationlibre
github_username:  libertic

# Build settings
markdown: kramdown
theme: minima

environment: prod


sass:
    sass_dir: _sass
    style: compressed

